config/routes.rb
Tinytalk::Application.routes.draw do
  


  get "headshot_demo/index"

  post "headshot/capture" => 'headshot#capture', :as => :headshot_capture

  resources :pins
  resources :comments, only: [:create]

  devise_for :users

  root to: "home#signin"

  match "index", to: "home#index"

  put "/update", to: "home#update"

  resources :boards do
    resources :pins
    resources :text_pins
  end

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description, :image, :board_id

  belongs_to :user
  belongs_to :board
  has_attached_file :image, styles: {medium: "320x240"}

  validates :description, presence: true
  validates :user_id, presence: true
  validates_attachment :image, presence:true,
                      content_type: {content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']},
                      size: {less_than: 5.megabytes }


end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  # GET /pins
  # GET /pins.json
  def index
    @board= Board.find(params[:board_id])
    @pins = @board.pins.order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])
    @board = params[:board_id]
    @comment = Comment.new
    @comments = Comment.where(commentable_type: Pin, commentable_id: @pin)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @board = Board.find(params[:board_id])
    @pin = current_user.pins.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @board = Board.find(params[:board_id])
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create

    @pin = current_user.pins.create(params[:pin])


    respond_to do |format|
      if @pin.save
        format.html { redirect_to "/boards/#{@pin.board_id}", notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @board = Board.find(params[:board_id])
    @pin = current_user.pins.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to board_pin_path(@board, @pin), notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @board = params[:board_id]
    @pin = current_user.pins.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to board_path(@board)}
      format.json { head :no_content }
    end
  end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.erb
<%= simple_form_for([@board, @pin], html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>


  <div class="form-inputs">
    <%= f.input :image, label: "Upload an Image" %>
    <%= f.input :description, as: :text, input_html:{rows: "3"} %>
    <%= f.hidden_field :board_id, value: @board.id %>
  </div>

  <div class="form-actions">
    <br>
    <%= f.button :submit, class: "btn btn-info" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div class="box">
    <%= link_to (image_tag pin.image(:medium)), board_pin_path(@board, pin) %>
    <p class="description">
    <%= pin.description %>
    </p>
    <p>
      <strong>
        Posted by <%= pin.user.email %>
      </strong>
    </p>

    <% if current_user == pin.user %>
      <p>
        <%= link_to 'Edit', edit_board_pin_path(@board,pin) %>
        <%= link_to 'Destroy', board_pin_path(@board,pin), method: :delete, data: { confirm: 'Are you sure?' } %>
      </p>
    <% end %>
</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Back', board_pin_path(@board, @pin) %>

app/views/pins/index.html.erb
<%= render 'home/signin' %>

<div id ="pins">
<% @pins.each do |pin| %>
  <div class="box">
      <%= image_tag pin.image(:medium) %>
      <p class="description">
      <%= pin.description %>
      </p>
      <p>
        <strong>
          Posted by <%= pin.user.email %>
        </strong>
      </p>
  </div>

<% end %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', board_path(@board) %>

app/views/pins/show.html.erb
<p>
  <%=image_tag @pin.image(:medium) %>
  <b>Description:</b>
  <%= @pin.description %>
  <%= @pin.user.email %>
</p>
<p>
  <% @comments.each do |comment| %>
    <p>
    <strong><%= User.find(comment.user_id).id %></strong>: <%= comment.content %>
    </p>
  <% end %>
</p>

<%= form_for @comment do |f| %>
  <%= f.text_area :content, placeholder: "Enter Comment Here" %>
  <%= f.hidden_field :commentable_type, value: "Pin" %>
  <%= f.hidden_field :commentable_id, value: @pin.id %>
  <%= f.hidden_field :board_id, value: @board %>
  <%= f.submit %>
<% end %>

<% if current_user == @pin.user %>
<%= link_to 'Edit', edit_board_pin_path(@board) %> |
<% end %>
<%= link_to 'Back', board_path(@board) %>

<br><br>