config/routes.rb
Tinytalk::Application.routes.draw do
  


  get "headshot_demo/index"

  post "headshot/capture" => 'headshot#capture', :as => :headshot_capture

  resources :pins
  resources :comments, only: [:create]

  devise_for :users

  root to: "home#signin"

  match "index", to: "home#index"

  put "/update", to: "home#update"

  resources :boards do
    resources :pins
    resources :text_pins
  end

end

app/models/text_pin.rb
class TextPin < ActiveRecord::Base
  attr_accessible :content, :title, :user_id, :board_id

  belongs_to :user
end

app/controllers/text_pins_controller.rb
class TextPinsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  # GET /text_pins
  # GET /text_pins.json
  def index
    @board= Board.find(params[:board_id])
    @text_pins = @board.text_pins.order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @text_pins }
    end
  end

  # GET /text_pins/1
  # GET /text_pins/1.json
  def show
    @text_pin = current_user.text_pins.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @text_pin }
    end
  end

  # GET /text_pins/new
  # GET /text_pins/new.json
  def new
    @board = Board.find(params[:board_id])
    @text_pin = current_user.text_pins.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @text_pin }
    end
  end

  # GET /text_pins/1/edit
  def edit
    @text_pin = current_user.text_pins.find(params[:id])
  end

  # POST /text_pins
  # POST /text_pins.json
  def create
    @text_pin = current_user.text_pins.create(params[:text_pin])

    respond_to do |format|
      if @text_pin.save
        format.html { redirect_to "/boards/#{@text_pin.board_id}", notice: 'Text pin was successfully created.' }
        format.json { render json: @text_pin, status: :created, location: @text_pin }
      else
        format.html { render action: "new" }
        format.json { render json: @text_pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /text_pins/1
  # PUT /text_pins/1.json
  def update
    @text_pin = current_user.text_pins.find(params[:id])

    respond_to do |format|
      if @text_pin.update_attributes(params[:text_pin])
        format.html { redirect_to @text_pin, notice: 'Text pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @text_pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /text_pins/1
  # DELETE /text_pins/1.json
  def destroy
    @text_pin = current_user.text_pins.find(params[:id])
    @text_pin.destroy

    respond_to do |format|
      format.html { redirect_to text_pins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/text_pins_helper.rb
module TextPinsHelper
end

app/views/text_pins/_form.html.erb
<%= simple_form_for([@board,@text_pin]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.hidden_field :board_id, value: @board.id %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/text_pins/_text_pin.html.erb
<div class="box">
  <%= text_pin.title %>
    <p class="description">
      <%= text_pin.content %>
    </p>
    <p>
      <strong>
        Posted by <%= text_pin.user.email %>
      </strong>
    </p>

    <% if current_user == text_pin.user %>
      <p>
        <%= link_to 'Edit', edit_board_text_pin_path(@board,text_pin) %>
        <%= link_to 'Destroy', board_text_pin_path(@board,text_pin), method: :delete, data: { confirm: 'Are you sure?' } %>
      </p>
    <% end %>
</div>

app/views/text_pins/edit.html.erb
<h1>Editing text_pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @text_pin %> |
<%= link_to 'Back', text_pins_path %>

app/views/text_pins/index.html.erb
<%= render 'home/signin' %>

<div id ="pins">
<% @text_pins.each do |pin| %>
  <div class="box">
    <p>
    <strong>
      <%= pin.title %>
      </strong>
      </p>
      <p class="description">
      <%= pin.content %>
      </p>

          Posted by <%= pin.user.email %>

  </div>

<% end %>
</div>

app/views/text_pins/new.html.erb
<h1>New text_pin</h1>

<%= render 'form' %>

<%= link_to 'Back', board_path(@board) %>

app/views/text_pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @text_pin.title %>
</p>

<p>
  <b>Content:</b>
  <%= @text_pin.content %>
</p>

<p>
  <b>User:</b>
  <%= @text_pin.user_id %>
</p>


<%= link_to 'Edit', edit_text_pin_path(@text_pin) %> |
<%= link_to 'Back', text_pins_path %>